name: Deploy to Heroku

on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    types:
      -  completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "srandom-app-frontend" #Must be unique in Heroku
          heroku_email: "kamyab.nazari@student.htw-berlin.de"
